- name: "manage worker1 and 2"
  hosts: ip-172-31-56-250
  become: true
  tasks:
  - name: "ensure Amit user exists"
    user:
      name: amit
      state: absent
  - name: "ensure Alex user exists"
    user:
      name: alex
      state: absent
      
